# The starting balance for new players
starting-balance: 1000.0

# Currency symbol
currency-symbol: "$"

# Messages
messages:
  balance:
    self: "&aYour balance is: &6{currency}{balance}"
    others: "&a{player}'s balance is: &6{currency}{balance}"
    usage: "&cUsage: /balance [player]"
    no-permission: "&cYou do not have permission to check others' balances."
    player-not-found: "&cPlayer {target} not found."
  pay:
    success: "&aYou have paid &6{currency}{amount} &ato &b{receiver}. Your new balance is &6{currency}{balance}"
    received: "&b{sender} &ahas paid you &6{currency}{amount}. Your new balance is &6{currency}{balance}"
    insufficient-funds: "&cYou do not have enough balance. Your balance is &6{currency}{balance}"
    invalid-amount: "&cInvalid amount."
    negative-amount: "&cAmount must be positive."
    pay-self: "&cYou cannot pay yourself."
    player-not-found: "&cPlayer {target} not found or not online."
    usage: "&cUsage: /pay <player> <amount>"
  economy:
    give: "&aYou have given &6{currency}{amount} &ato &b{player}. &aTheir new balance is &6{currency}{balance}"
    take: "&aYou have taken &6{currency}{amount} &afrom &b{player}. &aTheir new balance is &6{currency}{balance}"
    set: "&aYou have set &b{player}'s &abalance to &6{currency}{balance}"
    reload: "&aPlugin configuration reloaded."
    player-not-found: "&cPlayer {target} not found."
    invalid-amount: "&cInvalid amount."
    usage: "&cUsage: /economy <give|take|set|reload> [player] [amount]"
    no-permission: "&cYou do not have permission to use this command."
